# Generated by Django 3.0.8 on 2020-12-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_auto_20201130_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaagenda',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
